POST {{host}}/auth/sign-up
Content-Type: application/json

{
  "name": "test",
  "username": "again test",
  "password": "123123123"
}

###
POST {{host}}/auth/sign-in
Content-Type: application/json

{
  "username": "again test",
  "password": "123123123"
}

###
POST {{host}}/api/lists
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2MzU1MjMwMjIsImlhdCI6MTYzNTQ3OTgyMiwidXNlcl9pZCI6MX0.s8wDM9jGysz65UltrPlK1OXxI70rDILzFKfLsy6ZWRc